import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1769315526842 implements MigrationInterface {
    name = 'InitSchema1769315526842'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vehicle_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "iconUrl" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_6aa9a3b896b6d6c641e2d65c4fa" UNIQUE ("name"), CONSTRAINT "PK_204299912911cf175dd14b3ff78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6aa9a3b896b6d6c641e2d65c4f" ON "vehicle_categories" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."auth_credentials_authenticationmethod_enum" AS ENUM('local', 'google', 'facebook', 'apple')`);
        await queryRunner.query(`CREATE TABLE "auth_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "authenticationMethod" "public"."auth_credentials_authenticationmethod_enum" NOT NULL DEFAULT 'local', "password_hash" character varying, "salt" character varying, "oauthProviders" json, "password_reset_token" character varying, "password_reset_token_expires_at" TIMESTAMP WITH TIME ZONE, "mfa_enabled" boolean NOT NULL DEFAULT false, "last_password_change_at" TIMESTAMP WITH TIME ZONE, "failed_login_attempts" integer NOT NULL DEFAULT '0', "lockout_until" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, CONSTRAINT "UQ_ae974937597161faae307ff7539" UNIQUE ("password_reset_token"), CONSTRAINT "REL_8555dcc06a7fc7fa9844a5e724" UNIQUE ("user_id"), CONSTRAINT "PK_90fdced0865b5f15586e7cd3b25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_auth_credentials_password_reset_token" ON "auth_credentials" ("password_reset_token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_auth_credentials_user" ON "auth_credentials" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."sessions_sessiontype_enum" AS ENUM('web', 'mobile_app', 'api_client')`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionType" "public"."sessions_sessiontype_enum" NOT NULL DEFAULT 'web', "refreshTokenHash" text NOT NULL, "accessTokenExpiresAt" TIMESTAMP WITH TIME ZONE, "refreshTokenExpiresAt" TIMESTAMP WITH TIME ZONE, "lastSuccessfulLoginAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastActivityAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deviceInfo" json, "ipAddress" character varying(45), "userAgent" text, "location" json, "mfaVerified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "jti" character varying NOT NULL, "appAudience" character varying(50), "revoked" boolean NOT NULL DEFAULT false, "userId" uuid NOT NULL, CONSTRAINT "UQ_bd37bc320d2dc4a4cbbcd2993a1" UNIQUE ("jti"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b6d28f4cdc75f1de55b2fa619" ON "sessions" ("lastActivityAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccdc20a7bd41201c34422af46a" ON "sessions" ("lastSuccessfulLoginAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bd37bc320d2dc4a4cbbcd2993a" ON "sessions" ("jti") `);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_background_check_status_enum" AS ENUM('pending_background_check', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_driver_status_enum" AS ENUM('active', 'suspended', 'on_vacation', 'pending_docs', 'deactivated')`);
        await queryRunner.query(`CREATE TABLE "driver_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_license_number" character varying(50) NOT NULL, "driver_license_expiration_date" date NOT NULL, "driver_license_picture_url" character varying, "background_check_status" "public"."driver_profiles_background_check_status_enum" NOT NULL DEFAULT 'pending_background_check', "background_check_date" TIMESTAMP WITH TIME ZONE, "is_approved" boolean NOT NULL DEFAULT false, "emergencyContactInfo" json, "driver_status" "public"."driver_profiles_driver_status_enum" NOT NULL DEFAULT 'pending_docs', "paid_priority_until" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "user_id" uuid NOT NULL, CONSTRAINT "UQ_0d19c8c627861b4681a39ddd123" UNIQUE ("driver_license_number"), CONSTRAINT "REL_cec43742cd6dea0e8fcae3e29d" UNIQUE ("user_id"), CONSTRAINT "CHK_76b7a3e9a620c177daf41854fc" CHECK (("driver_status" <> 'active') OR ("is_approved" = true)), CONSTRAINT "CHK_b0511d62f64bcc0eb4350de660" CHECK (("background_check_status" <> 'rejected') OR ("is_approved" = false AND "driver_status" = 'suspended')), CONSTRAINT "CHK_12f2c4e80a9506cd7f5549b1a5" CHECK (("driver_status" <> 'deactivated') OR ("is_approved" = false)), CONSTRAINT "PK_6e002fc8a835351e070978fcad4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_affac4f174adfbc65e08090d5e" ON "driver_profiles" ("driver_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4372779be1a8a6d78dc8ae0263" ON "driver_profiles" ("is_approved") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1b913cc4fab0dcb63fa5b1be0" ON "driver_profiles" ("background_check_status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0d19c8c627861b4681a39ddd12" ON "driver_profiles" ("driver_license_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cec43742cd6dea0e8fcae3e29d" ON "driver_profiles" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."users_usertype_enum" AS ENUM('passenger', 'driver', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "email" character varying(150), "emailVerified" boolean NOT NULL DEFAULT false, "phoneNumber" character varying(20), "phoneNumberVerified" boolean NOT NULL DEFAULT false, "userType" "public"."users_usertype_enum" NOT NULL, "profilePictureUrl" character varying, "currentLocation" geography(Point,4326), "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "preferredLanguage" character varying(10), "termsAcceptedAt" TIMESTAMP WITH TIME ZONE, "privacyPolicyAcceptedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_1e3d0240b49c40521aaeb953293" UNIQUE ("phoneNumber"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82bbcdb9c42c5fe140291785c1" ON "users" ("userType") `);
        await queryRunner.query(`CREATE INDEX "IDX_79a26fedc89673cc9bf1218efe" ON "users" ("phoneNumberVerified") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e3d0240b49c40521aaeb95329" ON "users" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_19f0320dbf4e94fabff881c0be" ON "users" ("emailVerified") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_status_enum" AS ENUM('pending_review', 'approved', 'in_service', 'rejected', 'maintenance', 'unavailable')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "make" character varying(50) NOT NULL, "model" character varying(50) NOT NULL, "year" integer NOT NULL, "plate_number" character varying(15) NOT NULL, "color" character varying(30), "capacity" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "status" "public"."vehicles_status_enum" NOT NULL DEFAULT 'pending_review', "inspection_date" TIMESTAMP WITH TIME ZONE, "last_maintenance_date" TIMESTAMP WITH TIME ZONE, "mileage" bigint, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "driver_id" uuid NOT NULL, "driver_profile_id" uuid NOT NULL, "vehicle_type_id" uuid NOT NULL, CONSTRAINT "UQ_a7eeeb4b551b2629dd9ee964134" UNIQUE ("plate_number"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_vehicle_driver" ON "vehicles" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicle_driver_profile" ON "vehicles" ("driver_profile_id") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicle_vehicle_type" ON "vehicles" ("vehicle_type_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_vehicle_plate_number" ON "vehicles" ("plate_number") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicle_is_active" ON "vehicles" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_vehicle_status" ON "vehicles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_198957f5c5a1fa53aeaf2a0838" ON "vehicles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a6dc4b01790d8f2f0da40c2bc" ON "vehicles" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c6922f37d6f8a496a4cabfe08" ON "vehicles" ("vehicle_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7eeeb4b551b2629dd9ee96413" ON "vehicles" ("plate_number") `);
        await queryRunner.query(`CREATE TABLE "vehicle_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "base_fare" numeric(10,2) NOT NULL, "cost_per_km" numeric(10,4) NOT NULL, "cost_per_minute" numeric(10,4) NOT NULL, "min_fare" numeric(10,2) NOT NULL, "default_capacity" integer NOT NULL, "icon_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "category_id" uuid NOT NULL, CONSTRAINT "UQ_521e89eb074cfce4a101397064f" UNIQUE ("name"), CONSTRAINT "PK_73d1e40f4add7f4f6947acad3a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_644d70643ea994ca682cad546d" ON "vehicle_types" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "vehicle_service_classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "baseFareMultiplier" numeric(5,2) NOT NULL DEFAULT '1', "costPerKmMultiplier" numeric(5,2) NOT NULL DEFAULT '1', "costPerMinuteMultiplier" numeric(5,2) NOT NULL DEFAULT '1', "minFareMultiplier" numeric(5,2) NOT NULL DEFAULT '1', "minCapacity" integer NOT NULL, "maxCapacity" integer NOT NULL, "iconUrl" character varying(255), "displayOrder" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_125ec52e0728803f1f9bc6fef5b" UNIQUE ("name"), CONSTRAINT "PK_b29d938c1c028734d6d6bbd92ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_125ec52e0728803f1f9bc6fef5" ON "vehicle_service_classes" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymenttype_enum" AS ENUM('cash', 'card', 'wallet')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requested_amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'CUP', "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "payment_intent_id" character varying(100), "payment_gateway_response" jsonb, "payment_method_details" jsonb, "failure_reason" character varying(250), "paid_at" TIMESTAMP WITH TIME ZONE, "confirmed_by" uuid, "paymentType" "public"."orders_paymenttype_enum" NOT NULL DEFAULT 'cash', "metadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "trip_id" uuid NOT NULL, "passenger_id" uuid NOT NULL, "driver_id" uuid NOT NULL, CONSTRAINT "uq_orders_trip" UNIQUE ("trip_id"), CONSTRAINT "REL_e446d91b54e6c76f9fb5e707f9" UNIQUE ("trip_id"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_orders_passenger" ON "orders" ("passenger_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."trip_event_type" AS ENUM('trip_requested', 'driver_assigned', 'driver_offered', 'driver_accepted', 'driver_arrived_pickup', 'driver_en_route', 'trip_started', 'trip_completed', 'trip_canceled', 'payment_failed', 'payment_confirmed', 'no_drivers_found', 'fare_recalculated', 'driver_rejected', 'pickup_point_changed', 'dropoff_point_changed', 'location_update', 'discount_applied', 'penalty_applied', 'assigning_started', 'assignment_expired')`);
        await queryRunner.query(`CREATE TABLE "trip_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "event_type" "public"."trip_event_type" NOT NULL, "metadata" jsonb, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_e0724ddc5e207b265af9b27fe8" CHECK (occurred_at IS NOT NULL), CONSTRAINT "PK_df6ea3b2ad6f86f525d796220da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_trip_events_trip_occurred" ON "trip_events" ("trip_id", "occurred_at") `);
        await queryRunner.query(`CREATE INDEX "idx_trip_events_event_type" ON "trip_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_trip_events_trip_id" ON "trip_events" ("trip_id") `);
        await queryRunner.query(`CREATE TYPE "public"."assignment_status" AS ENUM('offered', 'accepted', 'rejected', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "trip_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."assignment_status" NOT NULL DEFAULT 'offered', "offered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "responded_at" TIMESTAMP WITH TIME ZONE, "ttl_expires_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "trip_id" uuid NOT NULL, "driver_id" uuid NOT NULL, "vehicle_id" uuid NOT NULL, CONSTRAINT "CHK_f517dc9e1df335b70848986f34" CHECK (("responded_at" IS NULL OR "responded_at" >= "offered_at")), CONSTRAINT "CHK_e7320f1fdb1884c3fc02b6723b" CHECK ("offered_at" IS NOT NULL), CONSTRAINT "PK_59753a59fa1dc5d52cdef2b1f10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trips_payment_mode_enum" AS ENUM('cash', 'card', 'wallet')`);
        await queryRunner.query(`CREATE TYPE "public"."trips_current_status_enum" AS ENUM('pending', 'assigning', 'accepted', 'arriving', 'in_progress', 'completed', 'cancelled', 'no_drivers_found')`);
        await queryRunner.query(`CREATE TABLE "trips" ("_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_mode" "public"."trips_payment_mode_enum" NOT NULL, "current_status" "public"."trips_current_status_enum" NOT NULL DEFAULT 'pending', "fare_estimated_total" numeric(10,2), "requested_at" TIMESTAMP WITH TIME ZONE NOT NULL, "accepted_at" TIMESTAMP WITH TIME ZONE, "pickup_eta_at" TIMESTAMP WITH TIME ZONE, "arrived_pickup_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "canceled_at" TIMESTAMP WITH TIME ZONE, "pickup_point" geography(Point,4326) NOT NULL, "pickup_address" text, "fare_final_currency" character(3), "fare_distance_km" numeric(10,3), "fare_duration_min" numeric(10,2), "fare_surge_multiplier" numeric(6,3) DEFAULT '1', "fare_total" numeric(10,2), "fare_breakdown" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "passenger_id" uuid NOT NULL, "driver_id" uuid, "vehicle_id" uuid, "order_id" uuid, "requested_vehicle_category_id" uuid, "requested_service_class_id" uuid, "estimate_vehicle_type_id" uuid, CONSTRAINT "REL_8b3534829163c67172ad780549" UNIQUE ("order_id"), CONSTRAINT "PK_b01d94eda4162cfa351d5775c67" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_trips_est_vehicle_type" ON "trips" ("estimate_vehicle_type_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_req_service_class" ON "trips" ("requested_service_class_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_req_vehicle_category" ON "trips" ("requested_vehicle_category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_requested_at" ON "trips" ("requested_at") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_vehicle" ON "trips" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_driver" ON "trips" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_passenger" ON "trips" ("passenger_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_status" ON "trips" ("current_status") `);
        await queryRunner.query(`CREATE TABLE "trip_stops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "seq" integer NOT NULL, "point" geography(Point,4326) NOT NULL, "address" text, "place_id" text, "planned_arrival_at" TIMESTAMP WITH TIME ZONE, "reached_at" TIMESTAMP WITH TIME ZONE, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_57494e98627d9b5d1161558115" CHECK (("reached_at" IS NULL OR "planned_arrival_at" IS NULL OR "reached_at" >= "planned_arrival_at")), CONSTRAINT "CHK_674aff99336bbaf6b4e263be52" CHECK ("seq" >= 0), CONSTRAINT "PK_876633f878970267cb0dc525984" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "gix_trip_stops_point" ON "trip_stops" USING GiST ("point") `);
        await queryRunner.query(`CREATE INDEX "idx_trip_stops_place_id" ON "trip_stops" ("place_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trip_stops_trip_id" ON "trip_stops" ("trip_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_trip_stops_trip_seq" ON "trip_stops" ("trip_id", "seq") `);
        await queryRunner.query(`CREATE TABLE "trip_snapshots" ("trip_id" uuid NOT NULL, "driver_name" text NOT NULL, "driver_phone" text, "vehicle_make" text NOT NULL, "vehicle_model" text NOT NULL, "vehicle_color" text, "vehicle_plate" text NOT NULL, "service_class_name" text NOT NULL, "captured_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_ce8d8fbdb0b737e412d72829b66" PRIMARY KEY ("trip_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('charge', 'commission_deduction', 'wallet_topup', 'payout', 'bonus', 'penalty', 'refund', 'plan_purchase', 'platform_comission')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('pending', 'processed', 'failed', 'reversed')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."transactions_type_enum" NOT NULL, "gross_amount" numeric(12,2) NOT NULL, "platform_fee_amount" numeric(12,2) NOT NULL DEFAULT '0', "net_amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'CUP', "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'pending', "processed_at" TIMESTAMP WITH TIME ZONE, "description" character varying(250), "metadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "order_id" uuid, "trip_id" uuid, "from_user_id" uuid, "to_user_id" uuid, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tx_from_user" ON "transactions" ("from_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tx_to_user" ON "transactions" ("to_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_35fc4b83a39ef23f08a4b5ac9c" ON "transactions" ("type", "status") `);
        await queryRunner.query(`CREATE TABLE "prepaid_plans" ("_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "trips_included" integer, "discount_pct" numeric(5,2), "fixed_discount_amount" numeric(12,2), "expires_in_days" integer, "price" numeric(12,2) NOT NULL, "currency" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "plan_features" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(), CONSTRAINT "PK_8985ddbaa6bbd6b4f8adab9a05b" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_prepaid_plans_active_currency" ON "prepaid_plans" ("is_active", "currency") `);
        await queryRunner.query(`CREATE INDEX "idx_prepaid_plans_active" ON "prepaid_plans" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."user_prepaid_plans_status_enum" AS ENUM('active', 'used', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "user_prepaid_plans" ("_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "purchase_date" TIMESTAMP NOT NULL DEFAULT NOW(), "expiration_date" TIMESTAMP, "trips_remaining" integer, "status" "public"."user_prepaid_plans_status_enum" NOT NULL DEFAULT 'active', "initial_purchase_transaction_id" uuid, "last_used_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(), CONSTRAINT "PK_6f909ca96206ce4deeb8179f810" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_upplans_status_trips" ON "user_prepaid_plans" ("status", "trips_remaining") `);
        await queryRunner.query(`CREATE INDEX "idx_upplans_user_status_exp" ON "user_prepaid_plans" ("user_id", "status", "expiration_date") `);
        await queryRunner.query(`CREATE INDEX "idx_upplans_user" ON "user_prepaid_plans" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "commission_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adjustment_seq" character varying(60) NOT NULL, "delta_fee" numeric(12,2) NOT NULL, "original_fee" numeric(12,2) NOT NULL, "new_fee" numeric(12,2) NOT NULL, "reason" character varying(200), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "order_id" uuid NOT NULL, CONSTRAINT "uq_comm_adj_order_seq" UNIQUE ("order_id", "adjustment_seq"), CONSTRAINT "PK_73900c0ca238cd02442ea013721" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_comm_adj_order" ON "commission_adjustments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comm_adj_order_seq" ON "commission_adjustments" ("adjustment_seq") `);
        await queryRunner.query(`CREATE TABLE "driver_balance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "current_wallet_balance" numeric(14,2) NOT NULL DEFAULT '0', "held_wallet_balance" numeric(14,2) NOT NULL DEFAULT '0', "total_earned_from_trips" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'CUP', "last_payout_at" TIMESTAMP WITH TIME ZONE, "min_payout_threshold" numeric(12,2) NOT NULL DEFAULT '0', "payout_method_id" uuid, "status" character varying(20) NOT NULL DEFAULT 'active', "blocked_at" TIMESTAMP WITH TIME ZONE, "blocked_reason" character varying(250), "unblocked_at" TIMESTAMP WITH TIME ZONE, "unblocked_by" uuid, "allowed_negative_limit" numeric(14,2) DEFAULT '0', "version" integer NOT NULL, "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_75d2458c9255fc9f2f9bdd94539" UNIQUE ("driver_id"), CONSTRAINT "REL_75d2458c9255fc9f2f9bdd9453" UNIQUE ("driver_id"), CONSTRAINT "PK_1f8b24e02a90cab2c22c0b72e1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_driver_balance_driver" ON "driver_balance" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "idx_driver_balance_status" ON "driver_balance" ("status") `);
        await queryRunner.query(`CREATE TABLE "wallet_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transaction_id" uuid, "amount" numeric(14,2) NOT NULL DEFAULT '0', "previous_balance" numeric(14,2) NOT NULL DEFAULT '0', "new_balance" numeric(14,2) NOT NULL DEFAULT '0', "note" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "walletId" uuid, CONSTRAINT "PK_721031746a6636132b3269be761" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_availability_availability_reason_enum" AS ENUM('OFFLINE', 'ON_TRIP', 'UNAVAILABLE')`);
        await queryRunner.query(`CREATE TABLE "drivers_availability" ("_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "is_online" boolean NOT NULL DEFAULT false, "is_available_for_trips" boolean NOT NULL DEFAULT false, "last_location" geography(Point,4326), "last_location_timestamp" TIMESTAMP WITH TIME ZONE, "current_trip_id" uuid, "current_vehicle_id" uuid, "last_online_timestamp" TIMESTAMP WITH TIME ZONE, "last_presence_timestamp" TIMESTAMP WITH TIME ZONE, "availability_reason" "public"."drivers_availability_availability_reason_enum", "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_13440dcaa3393ed3592a4620ea" UNIQUE ("driver_id"), CONSTRAINT "REL_7a27bbb8bb4680e85104737388" UNIQUE ("current_trip_id"), CONSTRAINT "PK_2e8626d5a2cd4a97bbd42f0989c" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "idx_drv_av_matchable" ON "drivers_availability" ("is_online", "is_available_for_trips") WHERE "is_online" = true AND "is_available_for_trips" = true AND "availability_reason" IS NULL AND "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_drv_av_last_presence_ts" ON "drivers_availability" ("last_presence_timestamp") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_drv_av_online_available" ON "drivers_availability" ("is_online", "is_available_for_trips") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_drv_av_available" ON "drivers_availability" ("is_available_for_trips") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_drv_av_online" ON "drivers_availability" ("is_online") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_drv_av_trip_active" ON "drivers_availability" ("current_trip_id") WHERE "current_trip_id" IS NOT NULL AND "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_drv_av_driver_active" ON "drivers_availability" ("driver_id") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."idempotency_keys_status_enum" AS ENUM('in_progress', 'succeeded', 'failed')`);
        await queryRunner.query(`CREATE TABLE "idempotency_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" text NOT NULL, "method" character varying(10) NOT NULL, "endpoint" character varying(120) NOT NULL, "user_id" uuid, "tenant_id" uuid, "request_hash" character(64), "status" "public"."idempotency_keys_status_enum" NOT NULL DEFAULT 'in_progress', "locked_at" TIMESTAMP WITH TIME ZONE, "locked_until" TIMESTAMP WITH TIME ZONE, "attempt_count" integer NOT NULL DEFAULT '0', "first_request_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_request_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "response_code" integer, "response_headers" jsonb, "response_body" jsonb, "error_code" text, "error_details" jsonb, "idempotency_window_sec" integer NOT NULL DEFAULT '86400', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0afd83cbf08c9d12089a9bffc5e" UNIQUE ("key"), CONSTRAINT "PK_8ad20779ad0411107a56e53d0f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5fc0731b6752a8e9194fa265e" ON "idempotency_keys" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2dc6ed32729e093c2228f175db" ON "idempotency_keys" ("user_id", "endpoint", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cash_collection_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "address" character varying(250), "location" geography(Point,4326), "contact_phone" character varying(30), "opening_hours" jsonb, "is_active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e600c7d74bda99668b8e92da6dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13df9bf76faec0f72364510d74" ON "cash_collection_points" ("is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."cash_collection_records_status_enum" AS ENUM('pending', 'completed')`);
        await queryRunner.query(`CREATE TABLE "cash_collection_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'CUP', "status" "public"."cash_collection_records_status_enum" NOT NULL DEFAULT 'pending', "notes" character varying(250), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "driver_id" uuid NOT NULL, "collection_point_id" uuid NOT NULL, "collected_by_user_id" uuid NOT NULL, "transaction_id" uuid NOT NULL, CONSTRAINT "uq_ccr_transaction" UNIQUE ("transaction_id"), CONSTRAINT "REL_035d4cda68736b296acd2ae47e" UNIQUE ("transaction_id"), CONSTRAINT "PK_8ccf0e5d6a4b5dfcdac5f327167" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ccr_driver" ON "cash_collection_records" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ccr_collected_by" ON "cash_collection_records" ("collected_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c9c8a4c4dbf05f6db01a216cc" ON "cash_collection_records" ("status") `);
        await queryRunner.query(`CREATE TABLE "zone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "cityId" uuid NOT NULL, "name" text NOT NULL, "kind" text, "priority" integer NOT NULL DEFAULT '100', "geom" geometry(MultiPolygon,4326) NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_zone_city_name" UNIQUE ("cityId", "name"), CONSTRAINT "ck_zone_geom_valid_srid_4326" CHECK (ST_SRID("geom") = 4326 AND ST_IsValid("geom")), CONSTRAINT "ck_zone_priority_gte_0" CHECK ("priority" >= 0), CONSTRAINT "PK_bd3989e5a3c3fb5ed546dfaf832" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_zone_active" ON "zone" ("active") `);
        await queryRunner.query(`CREATE INDEX "idx_zone_geom" ON "zone" USING GiST ("geom") `);
        await queryRunner.query(`CREATE INDEX "idx_zone_priority" ON "zone" ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_zone_name" ON "zone" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_zone_city" ON "zone" ("cityId") `);
        await queryRunner.query(`CREATE TABLE "city" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" text NOT NULL, "countryCode" character(2) NOT NULL, "timezone" text NOT NULL, "geom" geometry(MultiPolygon,4326), "active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_city_name_country" UNIQUE ("name", "countryCode"), CONSTRAINT "ck_city_geom_valid_srid_4326" CHECK ("geom" IS NULL OR (ST_SRID("geom") = 4326 AND ST_IsValid("geom"))), CONSTRAINT "ck_city_country_code_iso2" CHECK ("countryCode" ~ '^[A-Z]{2}$'), CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_city_geom" ON "city" USING GiST ("geom") `);
        await queryRunner.query(`CREATE INDEX "idx_city_active" ON "city" ("active") `);
        await queryRunner.query(`CREATE INDEX "idx_city_country" ON "city" ("countryCode") `);
        await queryRunner.query(`CREATE INDEX "idx_city_name" ON "city" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."price_policy_scopetype_enum" AS ENUM('GLOBAL', 'CITY', 'ZONE')`);
        await queryRunner.query(`CREATE TABLE "price_policy" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" text NOT NULL, "scopeType" "public"."price_policy_scopetype_enum" NOT NULL, "cityId" uuid, "zoneId" uuid, "active" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '100', "effectiveFrom" TIMESTAMP WITH TIME ZONE, "effectiveTo" TIMESTAMP WITH TIME ZONE, "timezone" text NOT NULL DEFAULT 'UTC', "conditions" jsonb NOT NULL DEFAULT '{}'::jsonb, "price" jsonb NOT NULL, "updatedBy" uuid, CONSTRAINT "ck_price_policy_scope_coherence" CHECK ((
    ("scopeType" = 'GLOBAL' AND "cityId" IS NULL AND "zoneId" IS NULL) OR
    ("scopeType" = 'CITY'   AND "cityId" IS NOT NULL AND "zoneId" IS NULL) OR
    ("scopeType" = 'ZONE'   AND "zoneId" IS NOT NULL AND "cityId" IS NULL)
  )), CONSTRAINT "ck_price_policy_effective_window" CHECK ("effectiveTo" IS NULL OR "effectiveFrom" IS NULL OR "effectiveTo" > "effectiveFrom"), CONSTRAINT "ck_price_policy_priority_gte_0" CHECK ("priority" >= 0), CONSTRAINT "PK_b4a4af00f42968ed56ad13bd375" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_price_policy_effective" ON "price_policy" ("effectiveFrom", "effectiveTo") `);
        await queryRunner.query(`CREATE INDEX "idx_price_policy_priority" ON "price_policy" ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_price_policy_active" ON "price_policy" ("active") `);
        await queryRunner.query(`CREATE INDEX "idx_price_policy_zone" ON "price_policy" ("zoneId") `);
        await queryRunner.query(`CREATE INDEX "idx_price_policy_city" ON "price_policy" ("cityId") `);
        await queryRunner.query(`CREATE INDEX "idx_price_policy_scope" ON "price_policy" ("scopeType") `);
        await queryRunner.query(`CREATE TABLE "outbox_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(120) NOT NULL, "payload" jsonb NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "sent_at" TIMESTAMP WITH TIME ZONE, "fail_reason" text, CONSTRAINT "PK_6689a16c00d09b8089f6237f1d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc0d2a98103923a41a9aebc384" ON "outbox_events" ("status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "vehicle_type_service_classes" ("vehicle_type_id" uuid NOT NULL, "service_class_id" uuid NOT NULL, CONSTRAINT "PK_1081216c8559c7dd016f6e0491d" PRIMARY KEY ("vehicle_type_id", "service_class_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_06e1f47ab0adc57a8faa32e0a1" ON "vehicle_type_service_classes" ("vehicle_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b792d3b795cd334ba3c4991f7" ON "vehicle_type_service_classes" ("service_class_id") `);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ADD CONSTRAINT "FK_8555dcc06a7fc7fa9844a5e7245" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_profiles" ADD CONSTRAINT "FK_cec43742cd6dea0e8fcae3e29d8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_9c2e0a8772c9e43b32f57bfcfcc" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_db828ac183742a8309756ad49c2" FOREIGN KEY ("driver_profile_id") REFERENCES "driver_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_8c6922f37d6f8a496a4cabfe080" FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_types" ADD CONSTRAINT "FK_644d70643ea994ca682cad546db" FOREIGN KEY ("category_id") REFERENCES "vehicle_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e446d91b54e6c76f9fb5e707f9d" FOREIGN KEY ("trip_id") REFERENCES "trips"("_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_03558df2912bb5af97d697a56c3" FOREIGN KEY ("passenger_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_222cd7bf166a2d7a6aad9cdebee" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_events" ADD CONSTRAINT "FK_7f990838ba955f659ec0abfcb31" FOREIGN KEY ("trip_id") REFERENCES "trips"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_assignments" ADD CONSTRAINT "FK_6000052ad36464298104954ec38" FOREIGN KEY ("trip_id") REFERENCES "trips"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_assignments" ADD CONSTRAINT "FK_59ce02adfde093fd6bae13da345" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_assignments" ADD CONSTRAINT "FK_382c4aad3e734367864fe60ecf7" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_3726f65f3c4106878e8a8bf3349" FOREIGN KEY ("passenger_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_44d36110fb38f45c2f15c946ddb" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_ab4b806373c2ee43946679d572e" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_8b3534829163c67172ad780549d" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_87d510881d06aecb8ee1c9de62f" FOREIGN KEY ("requested_vehicle_category_id") REFERENCES "vehicle_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_956edc7707d758b16f7116cec8c" FOREIGN KEY ("requested_service_class_id") REFERENCES "vehicle_service_classes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_442824a115f290eb4384d020852" FOREIGN KEY ("estimate_vehicle_type_id") REFERENCES "vehicle_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_stops" ADD CONSTRAINT "FK_5cb5ec6432abdf6f1e1c3a0970c" FOREIGN KEY ("trip_id") REFERENCES "trips"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_3cb0558ed36997f1d9ecc1118e7" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_cdaa32cc93d34c09c4f84aec6bb" FOREIGN KEY ("trip_id") REFERENCES "trips"("_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2f91a8175c49ac211314033e208" FOREIGN KEY ("from_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_cab8dd57a6d6d100a21ddc74679" FOREIGN KEY ("to_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_prepaid_plans" ADD CONSTRAINT "FK_84954d786dd190cf178eeef0c7e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_prepaid_plans" ADD CONSTRAINT "FK_304f2074e118a641c61e44d732c" FOREIGN KEY ("plan_id") REFERENCES "prepaid_plans"("_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commission_adjustments" ADD CONSTRAINT "FK_31c9bf69eca7b84022b726e77c1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_balance" ADD CONSTRAINT "FK_75d2458c9255fc9f2f9bdd94539" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_movements" ADD CONSTRAINT "FK_3f3b8eeb9a84ea2c805380d970b" FOREIGN KEY ("walletId") REFERENCES "driver_balance"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers_availability" ADD CONSTRAINT "FK_13440dcaa3393ed3592a4620ea5" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers_availability" ADD CONSTRAINT "FK_7a27bbb8bb4680e851047373885" FOREIGN KEY ("current_trip_id") REFERENCES "trips"("_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers_availability" ADD CONSTRAINT "FK_2df388375ba10b9219874130fb0" FOREIGN KEY ("current_vehicle_id") REFERENCES "vehicles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" ADD CONSTRAINT "FK_bfd4af17e546cd4f4fe94076807" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" ADD CONSTRAINT "FK_5843c5167bf102468b98f0f4808" FOREIGN KEY ("collection_point_id") REFERENCES "cash_collection_points"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" ADD CONSTRAINT "FK_d580b66602cb2ad89f93ff5503f" FOREIGN KEY ("collected_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" ADD CONSTRAINT "FK_035d4cda68736b296acd2ae47e1" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zone" ADD CONSTRAINT "FK_fd888d571e58d1d50c70fc9d755" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_policy" ADD CONSTRAINT "FK_855207eb47107ef942f32430b13" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_policy" ADD CONSTRAINT "FK_375a6be90874473b52c5e3ea80d" FOREIGN KEY ("zoneId") REFERENCES "zone"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_type_service_classes" ADD CONSTRAINT "FK_06e1f47ab0adc57a8faa32e0a11" FOREIGN KEY ("vehicle_type_id") REFERENCES "vehicle_types"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle_type_service_classes" ADD CONSTRAINT "FK_9b792d3b795cd334ba3c4991f73" FOREIGN KEY ("service_class_id") REFERENCES "vehicle_service_classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle_type_service_classes" DROP CONSTRAINT "FK_9b792d3b795cd334ba3c4991f73"`);
        await queryRunner.query(`ALTER TABLE "vehicle_type_service_classes" DROP CONSTRAINT "FK_06e1f47ab0adc57a8faa32e0a11"`);
        await queryRunner.query(`ALTER TABLE "price_policy" DROP CONSTRAINT "FK_375a6be90874473b52c5e3ea80d"`);
        await queryRunner.query(`ALTER TABLE "price_policy" DROP CONSTRAINT "FK_855207eb47107ef942f32430b13"`);
        await queryRunner.query(`ALTER TABLE "zone" DROP CONSTRAINT "FK_fd888d571e58d1d50c70fc9d755"`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" DROP CONSTRAINT "FK_035d4cda68736b296acd2ae47e1"`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" DROP CONSTRAINT "FK_d580b66602cb2ad89f93ff5503f"`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" DROP CONSTRAINT "FK_5843c5167bf102468b98f0f4808"`);
        await queryRunner.query(`ALTER TABLE "cash_collection_records" DROP CONSTRAINT "FK_bfd4af17e546cd4f4fe94076807"`);
        await queryRunner.query(`ALTER TABLE "drivers_availability" DROP CONSTRAINT "FK_2df388375ba10b9219874130fb0"`);
        await queryRunner.query(`ALTER TABLE "drivers_availability" DROP CONSTRAINT "FK_7a27bbb8bb4680e851047373885"`);
        await queryRunner.query(`ALTER TABLE "drivers_availability" DROP CONSTRAINT "FK_13440dcaa3393ed3592a4620ea5"`);
        await queryRunner.query(`ALTER TABLE "wallet_movements" DROP CONSTRAINT "FK_3f3b8eeb9a84ea2c805380d970b"`);
        await queryRunner.query(`ALTER TABLE "driver_balance" DROP CONSTRAINT "FK_75d2458c9255fc9f2f9bdd94539"`);
        await queryRunner.query(`ALTER TABLE "commission_adjustments" DROP CONSTRAINT "FK_31c9bf69eca7b84022b726e77c1"`);
        await queryRunner.query(`ALTER TABLE "user_prepaid_plans" DROP CONSTRAINT "FK_304f2074e118a641c61e44d732c"`);
        await queryRunner.query(`ALTER TABLE "user_prepaid_plans" DROP CONSTRAINT "FK_84954d786dd190cf178eeef0c7e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_cab8dd57a6d6d100a21ddc74679"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2f91a8175c49ac211314033e208"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_cdaa32cc93d34c09c4f84aec6bb"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_3cb0558ed36997f1d9ecc1118e7"`);
        await queryRunner.query(`ALTER TABLE "trip_stops" DROP CONSTRAINT "FK_5cb5ec6432abdf6f1e1c3a0970c"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_442824a115f290eb4384d020852"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_956edc7707d758b16f7116cec8c"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_87d510881d06aecb8ee1c9de62f"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_8b3534829163c67172ad780549d"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_ab4b806373c2ee43946679d572e"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_44d36110fb38f45c2f15c946ddb"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_3726f65f3c4106878e8a8bf3349"`);
        await queryRunner.query(`ALTER TABLE "trip_assignments" DROP CONSTRAINT "FK_382c4aad3e734367864fe60ecf7"`);
        await queryRunner.query(`ALTER TABLE "trip_assignments" DROP CONSTRAINT "FK_59ce02adfde093fd6bae13da345"`);
        await queryRunner.query(`ALTER TABLE "trip_assignments" DROP CONSTRAINT "FK_6000052ad36464298104954ec38"`);
        await queryRunner.query(`ALTER TABLE "trip_events" DROP CONSTRAINT "FK_7f990838ba955f659ec0abfcb31"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_222cd7bf166a2d7a6aad9cdebee"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_03558df2912bb5af97d697a56c3"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e446d91b54e6c76f9fb5e707f9d"`);
        await queryRunner.query(`ALTER TABLE "vehicle_types" DROP CONSTRAINT "FK_644d70643ea994ca682cad546db"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_8c6922f37d6f8a496a4cabfe080"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_db828ac183742a8309756ad49c2"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_9c2e0a8772c9e43b32f57bfcfcc"`);
        await queryRunner.query(`ALTER TABLE "driver_profiles" DROP CONSTRAINT "FK_cec43742cd6dea0e8fcae3e29d8"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" DROP CONSTRAINT "FK_8555dcc06a7fc7fa9844a5e7245"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b792d3b795cd334ba3c4991f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06e1f47ab0adc57a8faa32e0a1"`);
        await queryRunner.query(`DROP TABLE "vehicle_type_service_classes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc0d2a98103923a41a9aebc384"`);
        await queryRunner.query(`DROP TABLE "outbox_events"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_policy_scope"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_policy_city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_policy_zone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_policy_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_policy_priority"`);
        await queryRunner.query(`DROP INDEX "public"."idx_price_policy_effective"`);
        await queryRunner.query(`DROP TABLE "price_policy"`);
        await queryRunner.query(`DROP TYPE "public"."price_policy_scopetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_city_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_city_country"`);
        await queryRunner.query(`DROP INDEX "public"."idx_city_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_city_geom"`);
        await queryRunner.query(`DROP TABLE "city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zone_city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zone_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zone_priority"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zone_geom"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zone_active"`);
        await queryRunner.query(`DROP TABLE "zone"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c9c8a4c4dbf05f6db01a216cc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ccr_collected_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ccr_driver"`);
        await queryRunner.query(`DROP TABLE "cash_collection_records"`);
        await queryRunner.query(`DROP TYPE "public"."cash_collection_records_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13df9bf76faec0f72364510d74"`);
        await queryRunner.query(`DROP TABLE "cash_collection_points"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc6ed32729e093c2228f175db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5fc0731b6752a8e9194fa265e"`);
        await queryRunner.query(`DROP TABLE "idempotency_keys"`);
        await queryRunner.query(`DROP TYPE "public"."idempotency_keys_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_drv_av_driver_active"`);
        await queryRunner.query(`DROP INDEX "public"."uq_drv_av_trip_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drv_av_online"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drv_av_available"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drv_av_online_available"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drv_av_last_presence_ts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drv_av_matchable"`);
        await queryRunner.query(`DROP TABLE "drivers_availability"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_availability_availability_reason_enum"`);
        await queryRunner.query(`DROP TABLE "wallet_movements"`);
        await queryRunner.query(`DROP INDEX "public"."idx_driver_balance_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_driver_balance_driver"`);
        await queryRunner.query(`DROP TABLE "driver_balance"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comm_adj_order_seq"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comm_adj_order"`);
        await queryRunner.query(`DROP TABLE "commission_adjustments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_upplans_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_upplans_user_status_exp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_upplans_status_trips"`);
        await queryRunner.query(`DROP TABLE "user_prepaid_plans"`);
        await queryRunner.query(`DROP TYPE "public"."user_prepaid_plans_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prepaid_plans_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_prepaid_plans_active_currency"`);
        await queryRunner.query(`DROP TABLE "prepaid_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35fc4b83a39ef23f08a4b5ac9c"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tx_to_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tx_from_user"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "trip_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."ux_trip_stops_trip_seq"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trip_stops_trip_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trip_stops_place_id"`);
        await queryRunner.query(`DROP INDEX "public"."gix_trip_stops_point"`);
        await queryRunner.query(`DROP TABLE "trip_stops"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_passenger"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_driver"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_vehicle"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_requested_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_req_vehicle_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_req_service_class"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_est_vehicle_type"`);
        await queryRunner.query(`DROP TABLE "trips"`);
        await queryRunner.query(`DROP TYPE "public"."trips_current_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trips_payment_mode_enum"`);
        await queryRunner.query(`DROP TABLE "trip_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignment_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trip_events_trip_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trip_events_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trip_events_trip_occurred"`);
        await queryRunner.query(`DROP TABLE "trip_events"`);
        await queryRunner.query(`DROP TYPE "public"."trip_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_passenger"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymenttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_125ec52e0728803f1f9bc6fef5"`);
        await queryRunner.query(`DROP TABLE "vehicle_service_classes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_644d70643ea994ca682cad546d"`);
        await queryRunner.query(`DROP TABLE "vehicle_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7eeeb4b551b2629dd9ee96413"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c6922f37d6f8a496a4cabfe08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a6dc4b01790d8f2f0da40c2bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_198957f5c5a1fa53aeaf2a0838"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicle_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicle_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."uq_vehicle_plate_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicle_vehicle_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicle_driver_profile"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehicle_driver"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19f0320dbf4e94fabff881c0be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e3d0240b49c40521aaeb95329"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79a26fedc89673cc9bf1218efe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82bbcdb9c42c5fe140291785c1"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_usertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cec43742cd6dea0e8fcae3e29d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d19c8c627861b4681a39ddd12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1b913cc4fab0dcb63fa5b1be0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4372779be1a8a6d78dc8ae0263"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_affac4f174adfbc65e08090d5e"`);
        await queryRunner.query(`DROP TABLE "driver_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_driver_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_background_check_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd37bc320d2dc4a4cbbcd2993a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccdc20a7bd41201c34422af46a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b6d28f4cdc75f1de55b2fa619"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_sessiontype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_credentials_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_credentials_password_reset_token"`);
        await queryRunner.query(`DROP TABLE "auth_credentials"`);
        await queryRunner.query(`DROP TYPE "public"."auth_credentials_authenticationmethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6aa9a3b896b6d6c641e2d65c4f"`);
        await queryRunner.query(`DROP TABLE "vehicle_categories"`);
    }

}
